global using CommunityToolkit.Mvvm.ComponentModel;
global using CommunityToolkit.Mvvm.Input;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.UI;
global using Microsoft.UI.Xaml;
global using Microsoft.UI.Xaml.Controls;
global using Microsoft.UI.Xaml.Navigation;
global using Nexos_Creation.Common;
global using Nexos_Creation.ViewModels;
global using Nexos_Creation.Views;
global using WinUICommunity;
global using static Nexos_Creation.Common.AppHelper;
